2025-04-09 19:10:05,756 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 19:10:09,834 [CRITICAL] [req_id:None user:None] startup_check.py:18 - ‚ùå Database connection failed: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-04-09 19:10:09,835 [CRITICAL] [req_id:None user:None] lifespan.py:24 - ‚ùå Startup failed due to service connection error
2025-04-09 19:10:50,106 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 19:10:50,125 [DEBUG] [req_id:None user:None] connection.py:960 - caching sha2: Trying full auth...
2025-04-09 19:10:50,127 [DEBUG] [req_id:None user:None] connection.py:982 - -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyV25Sr7UWBMq6Ra4VJJI
pcD6PZam9wPQWt0dWBDSQhXkzy1Nhts8K8U8EnvSL60AK+eZwB1SqkmLMdmql6Zm
KpekZ7EAL52ITDu3Dvjjzw+Rp/2bZVR9cMYvTAWPhIlf02bFUbeNMLo9KeXcFLUx
1mDxZTZo69v0LiJxAhOLMhwKAclgVRJcvB9DnNcBb5yxljYrTaPibm+HEfvKhpd8
whPd5fdEcHVJ0KS8GZGTG0CneeR97UmJPYl1MZWlwZD7vDphre3vjf/rUITR0JDq
p9mp8/ZR3ZnrQGpKCJW/HKkEOuCZfyLkKej8wR8kChEpCuxz27DmdZHjhANW+R5A
CwIDAQAB
-----END PUBLIC KEY-----

2025-04-09 19:10:50,165 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 19:10:50,183 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 19:10:50,185 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 19:10:50,188 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 19:10:50,188 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 19:10:50,188 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 19:10:50,189 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 19:10:50,189 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 19:40:50.185545+09:00 (in 1799.996484 seconds)
2025-04-09 19:10:57,088 [INFO] [req_id:a75720e1-e35a-4818-ac46-90c3fa70118a user:None] base.py:43 - POST /auth/login/email [200] 0.1131s
2025-04-09 19:11:02,490 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 19:11:02,490 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 19:11:02,491 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:625 - Calling on_header_value with data[75:151]
2025-04-09 19:11:02,491 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 19:11:02,492 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:625 - Calling on_header_field with data[153:165]
2025-04-09 19:11:02,492 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:625 - Calling on_header_value with data[167:177]
2025-04-09 19:11:02,493 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 19:11:02,493 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 19:11:02,494 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:625 - Calling on_part_data with data[181:65717]
2025-04-09 19:11:02,496 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:625 - Calling on_part_data with data[0:262144]
2025-04-09 19:11:02,499 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:625 - Calling on_part_data with data[0:78441]
2025-04-09 19:11:02,500 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 19:11:02,500 [DEBUG] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 19:11:02,507 [INFO] [req_id:5bdef5b2-2f41-4b4e-a4ac-b9271c499a21 user:1] base.py:43 - POST /common/image [200] 0.0223s
2025-04-09 19:11:09,832 [INFO] [req_id:cc0733f6-7944-40f7-9f37-31978fa22cdb user:None] base.py:43 - GET /users/id/1 [200] 0.0197s
2025-04-09 19:11:13,041 [INFO] [req_id:2eec97ff-a306-4f8c-8c7e-ac2f2ee76054 user:None] base.py:43 - GET /users/email/jht@naver.com [200] 0.0174s
2025-04-09 19:11:17,558 [INFO] [req_id:84625bd8-78e7-4951-9b22-68ad8405d065 user:1] base.py:43 - GET /posts [200] 0.0176s
2025-04-09 19:19:38,892 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 19:19:38,893 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 19:19:38,894 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 19:19:38,894 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 19:19:38,894 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 19:19:38,896 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 19:19:41,599 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 19:19:41,621 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 19:19:41,638 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 19:19:41,645 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 19:19:41,647 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 19:19:41,650 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 19:19:41,650 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 19:19:41,651 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 19:19:41,651 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 19:19:41,651 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 19:49:41.647446+09:00 (in 1799.996001 seconds)
2025-04-09 19:20:11,828 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 19:20:11,828 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 19:20:11,829 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 19:20:11,829 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 19:20:11,829 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 19:20:11,830 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 19:20:14,393 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 19:20:14,413 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 19:20:14,428 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 19:20:14,436 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 19:20:14,439 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 19:20:14,440 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 19:20:14,441 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 19:20:14,441 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 19:20:14,442 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 19:20:14,442 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 19:50:14.439414+09:00 (in 1799.996996 seconds)
2025-04-09 19:20:44,606 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 19:20:44,607 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 19:20:44,609 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 19:20:44,612 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 19:20:44,613 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 19:20:44,614 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 19:20:46,651 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 19:20:46,667 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 19:20:46,680 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 19:20:46,687 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 19:20:46,689 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 19:20:46,690 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 19:20:46,690 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 19:20:46,691 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 19:20:46,691 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 19:20:46,692 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 19:50:46.688206+09:00 (in 1799.995999 seconds)
2025-04-09 19:20:53,287 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 19:20:53,288 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 19:20:53,288 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:625 - Calling on_header_value with data[75:151]
2025-04-09 19:20:53,288 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 19:20:53,289 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:625 - Calling on_header_field with data[153:165]
2025-04-09 19:20:53,289 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:625 - Calling on_header_value with data[167:177]
2025-04-09 19:20:53,289 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 19:20:53,290 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 19:20:53,290 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:625 - Calling on_part_data with data[181:262325]
2025-04-09 19:20:53,291 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:625 - Calling on_part_data with data[0:143977]
2025-04-09 19:20:53,291 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 19:20:53,292 [DEBUG] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 19:20:53,297 [INFO] [req_id:ab76f5dd-ded5-42b0-a609-4a190ab52803 user:1] base.py:43 - POST /common/image [200] 0.011s
2025-04-09 19:21:03,890 [WARNING] [req_id:5f6d175b-7c90-42ba-bd2d-69c3469ca8c2 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: A transaction is already begun on this Session.
2025-04-09 19:21:13,752 [INFO] [req_id:e9642425-e5af-4ae8-84d7-c68a390f71be user:1] utils.py:35 - ‚úÖ Ïù¥Îèô ÏôÑÎ£å: C:\Users\jht56\Documents\GitHub\fastapi-core\public\temp\623c7497-bd50-4d6e-9b15-2456fd2ef6ad.jpg ‚Üí C:\Users\jht56\Documents\GitHub\fastapi-core\public\posts\623c7497-bd50-4d6e-9b15-2456fd2ef6ad.jpg
2025-04-09 19:21:13,774 [INFO] [req_id:e9642425-e5af-4ae8-84d7-c68a390f71be user:1] base.py:43 - POST /posts [200] 0.0685s
2025-04-09 19:23:02,496 [WARNING] [req_id:ff7bb05e-42bd-4ee4-a1e6-d1385edee1a3 user:1] handlers.py:76 - Unhandled HTTPException: 500 - {'error': 'IMAGE_UPDATE_FAILED', 'message': 'Ïù¥ÎØ∏ÏßÄ ÏóÖÎç∞Ïù¥Ìä∏ Ï§ë Ïò§Î•ò Î∞úÏÉù. Î°§Î∞± ÏàòÌñâÎê®.', 'reason': '400: Ï°¥Ïû¨ÌïòÏßÄ ÏïäÎäî Ïù¥ÎØ∏ÏßÄÏûÖÎãàÎã§.'} | POST /posts
2025-04-09 19:23:02,497 [INFO] [req_id:ff7bb05e-42bd-4ee4-a1e6-d1385edee1a3 user:1] base.py:43 - POST /posts [500] 0.0299s
2025-04-09 19:50:46,682 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 19:50:46,684 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 19:50:46.688206+09:00 (in 0.003673 seconds)
2025-04-09 19:50:46,697 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 19:50:46,698 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:20:46.688206+09:00 (in 1799.989755 seconds)
2025-04-09 19:50:46,698 [INFO] [req_id:None user:None] base.py:129 - Running job "cleanup_temp_images (trigger: interval[0:30:00], next run at: 2025-04-09 20:20:46 KST)" (scheduled at 2025-04-09 19:50:46.688206+09:00)
2025-04-09 19:50:46,699 [INFO] [req_id:None user:None] temp_cleanup.py:35 - ‚úÖ Ïù¥Î≤à Ïã§ÌñâÏóêÏÑú ÏÇ≠Ï†úÎêú Ïù¥ÎØ∏ÏßÄ Ïàò: 0
2025-04-09 19:50:46,700 [INFO] [req_id:None user:None] base.py:156 - Job "cleanup_temp_images (trigger: interval[0:30:00], next run at: 2025-04-09 20:20:46 KST)" executed successfully
2025-04-09 19:50:46,837 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 19:50:46,838 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 19:50:46,839 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 19:50:46,839 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 19:50:46,840 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 19:50:46,840 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 19:50:49,645 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 19:50:49,667 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 19:50:49,685 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 19:50:49,691 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 19:50:49,694 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 19:50:49,696 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 19:50:49,696 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 19:50:49,697 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 19:50:49,697 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 19:50:49,697 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:20:49.694104+09:00 (in 1799.996524 seconds)
2025-04-09 19:55:47,778 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 19:55:47,781 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 19:55:47,781 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 19:55:47,782 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 19:55:47,782 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 19:55:47,782 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:06:28,284 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:06:28,308 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:06:28,323 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:06:28,328 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:06:28,331 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:06:28,333 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:06:28,333 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:06:28,334 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:06:28,334 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:06:28,335 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:36:28.330065+09:00 (in 1799.994910 seconds)
2025-04-09 20:06:58,436 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:06:58,437 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:06:58,439 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:06:58,439 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:06:58,439 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:06:58,440 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:07:00,577 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:07:00,600 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:07:00,619 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:07:00,625 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:07:00,626 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:07:00,628 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:07:00,628 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:07:00,629 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:07:00,629 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:07:00,629 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:37:00.626963+09:00 (in 1799.997002 seconds)
2025-04-09 20:11:58,827 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:11:58,828 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:11:58,830 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:11:58,831 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:11:58,832 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:11:58,833 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:12:01,147 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:12:01,168 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:12:01,183 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:12:01,199 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:12:01,201 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:12:01,203 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:12:01,203 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:12:01,203 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:12:01,204 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:12:01,204 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:42:01.201160+09:00 (in 1799.997000 seconds)
2025-04-09 20:16:59,654 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:16:59,656 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:16:59,658 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:16:59,658 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:16:59,658 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:16:59,659 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:17:02,312 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:17:02,332 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:17:02,351 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:17:02,357 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:17:02,359 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:17:02,362 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:17:02,362 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:17:02,362 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:17:02,362 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:17:02,363 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:47:02.359273+09:00 (in 1799.995948 seconds)
2025-04-09 20:17:32,451 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:17:32,452 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:17:32,453 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:17:32,453 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:17:32,453 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:17:32,454 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:17:34,657 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:17:34,680 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:17:34,696 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:17:34,703 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:17:34,705 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:17:34,707 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:17:34,707 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:17:34,707 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:17:34,707 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:17:34,708 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:47:34.705819+09:00 (in 1799.997001 seconds)
2025-04-09 20:22:32,839 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:22:32,840 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:22:32,840 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:22:32,840 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:22:32,841 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:22:32,841 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:22:35,474 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:22:35,500 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:22:35,520 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:22:35,529 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:22:35,530 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:22:35,532 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:22:35,533 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:22:35,533 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:22:35,533 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:22:35,534 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:52:35.530381+09:00 (in 1799.996204 seconds)
2025-04-09 20:23:05,638 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:23:05,639 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:23:05,639 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:23:05,640 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:23:05,640 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:23:05,641 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:23:07,765 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:23:07,792 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:23:07,819 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:23:07,827 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:23:07,829 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:23:07,830 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:23:07,831 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:23:07,831 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:23:07,832 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:23:07,832 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:53:07.829669+09:00 (in 1799.996993 seconds)
2025-04-09 20:28:06,013 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:28:06,014 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:28:06,015 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:28:06,015 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:28:06,017 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:28:06,019 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:28:07,955 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:28:07,975 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:28:07,991 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:28:07,999 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:28:08,000 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:28:08,002 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:28:08,002 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:28:08,003 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:28:08,003 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:28:08,003 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:58:08.000028+09:00 (in 1799.997005 seconds)
2025-04-09 20:28:09,923 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:28:09,951 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:28:09,964 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:28:09,974 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:28:09,975 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:28:09,977 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:28:09,977 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:28:09,977 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:28:09,977 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:28:09,978 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:58:09.975084+09:00 (in 1799.996484 seconds)
2025-04-09 20:29:18,866 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:29:18,867 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:29:18,868 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:29:18,868 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:29:18,869 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:29:18,871 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:29:20,801 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:29:20,818 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:29:20,833 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:29:20,838 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:29:20,841 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:29:20,843 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:29:20,843 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:29:20,843 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:29:20,844 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:29:20,844 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 20:59:20.840700+09:00 (in 1799.996332 seconds)
2025-04-09 20:33:20,608 [WARNING] [req_id:2cea3153-1c19-4ea7-b109-8abfe5dc1cd9 user:1] handlers.py:76 - Unhandled HTTPException: 404 - Not Found | POST /common/files
2025-04-09 20:33:20,610 [INFO] [req_id:2cea3153-1c19-4ea7-b109-8abfe5dc1cd9 user:1] base.py:43 - POST /common/files [404] 0.0031s
2025-04-09 20:33:20,802 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:33:20,804 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:33:20,804 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:33:20,804 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:33:20,805 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:33:20,806 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:33:22,720 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:33:22,738 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:33:22,752 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:33:22,758 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:33:22,760 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:33:22,761 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:33:22,761 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:33:22,762 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:33:22,762 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:33:22,763 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:03:22.760259+09:00 (in 1799.996935 seconds)
2025-04-09 20:33:24,550 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:33:24,566 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:33:24,584 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:33:24,589 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:33:24,591 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:33:24,593 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:33:24,595 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:33:24,596 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:33:24,596 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:33:24,596 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:03:24.591290+09:00 (in 1799.994822 seconds)
2025-04-09 20:33:28,220 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 20:33:28,221 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 20:33:28,221 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:625 - Calling on_header_value with data[75:156]
2025-04-09 20:33:28,221 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 20:33:28,221 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:625 - Calling on_header_field with data[158:170]
2025-04-09 20:33:28,222 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:625 - Calling on_header_value with data[172:182]
2025-04-09 20:33:28,222 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 20:33:28,222 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 20:33:28,223 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:625 - Calling on_part_data with data[186:65722]
2025-04-09 20:33:28,225 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:625 - Calling on_part_data with data[0:262144]
2025-04-09 20:33:28,227 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:625 - Calling on_part_data with data[0:78441]
2025-04-09 20:33:28,227 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 20:33:28,228 [DEBUG] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 20:33:28,241 [WARNING] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] handlers.py:35 - Validation failed: [{'type': 'missing', 'loc': ('body', 'file'), 'msg': 'Field required', 'input': None}]
2025-04-09 20:33:28,242 [INFO] [req_id:38778d56-7a89-4084-8329-8e6352934e45 user:1] base.py:43 - POST /common/files [422] 0.024s
2025-04-09 20:34:11,023 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 20:34:11,024 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 20:34:11,024 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:625 - Calling on_header_value with data[75:150]
2025-04-09 20:34:11,024 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 20:34:11,025 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:625 - Calling on_header_field with data[152:164]
2025-04-09 20:34:11,025 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:625 - Calling on_header_value with data[166:176]
2025-04-09 20:34:11,025 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 20:34:11,025 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 20:34:11,025 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:625 - Calling on_part_data with data[180:65716]
2025-04-09 20:34:11,027 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:625 - Calling on_part_data with data[0:262144]
2025-04-09 20:34:11,028 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:625 - Calling on_part_data with data[0:78441]
2025-04-09 20:34:11,028 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 20:34:11,028 [DEBUG] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 20:34:11,031 [INFO] [req_id:4eefa619-f6e2-4dd6-921e-fcab9bd08b37 user:1] base.py:43 - POST /common/files [200] 0.0103s
2025-04-09 20:34:52,497 [WARNING] [req_id:1bff013a-87fe-4167-921f-dacf81bf886b user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: (pymysql.err.ProgrammingError) (1146, "Table 'mysql-server.file' doesn't exist")
[SQL: SELECT file.post_id AS file_post_id, file.path AS file_path, file.original_name AS file_original_name, file.size AS file_size, file.type AS file_type, file.description AS file_description, file.is_main AS file_is_main, file.uploaded_at AS file_uploaded_at, file.owner_type AS file_owner_type, file.owner_id AS file_owner_id, file.id AS file_id, file.created_at AS file_created_at, file.updated_at AS file_updated_at 
FROM file 
WHERE file.post_id IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50 ... 3 parameters truncated ... 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 104)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-04-09 20:34:57,557 [WARNING] [req_id:1e83646b-01a2-4cb2-9038-d0d937955b66 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: (pymysql.err.ProgrammingError) (1146, "Table 'mysql-server.file' doesn't exist")
[SQL: SELECT file.post_id AS file_post_id, file.path AS file_path, file.original_name AS file_original_name, file.size AS file_size, file.type AS file_type, file.description AS file_description, file.is_main AS file_is_main, file.uploaded_at AS file_uploaded_at, file.owner_type AS file_owner_type, file.owner_id AS file_owner_id, file.id AS file_id, file.created_at AS file_created_at, file.updated_at AS file_updated_at 
FROM file 
WHERE file.post_id IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50 ... 3 parameters truncated ... 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 104)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-04-09 20:36:08,746 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:36:08,748 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:36:08,748 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:36:08,749 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:36:08,750 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:36:08,751 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:40:00,899 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:40:00,922 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:40:00,945 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:40:00,953 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:40:00,957 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:40:00,960 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:40:00,960 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:40:00,961 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:40:00,962 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:40:00,963 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:10:00.956087+09:00 (in 1799.992486 seconds)
2025-04-09 20:40:12,345 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:40:12,349 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:40:12,351 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:40:12,352 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:40:12,352 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:40:12,354 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:40:15,856 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:40:15,879 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:40:15,905 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:40:15,914 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:40:15,917 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:40:15,919 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:40:15,921 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:40:15,921 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:40:15,922 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:40:15,922 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:10:15.917949+09:00 (in 1799.995448 seconds)
2025-04-09 20:50:09,380 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:50:09,407 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:50:09,422 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:50:09,440 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:50:09,442 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:50:09,443 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:50:09,444 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:50:09,444 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:50:09,445 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:50:09,445 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:20:09.442806+09:00 (in 1799.997025 seconds)
2025-04-09 20:52:11,825 [WARNING] [req_id:3e47c986-9f6f-4800-83ee-31541f596b9e user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: A transaction is already begun on this Session.
2025-04-09 20:52:31,045 [WARNING] [req_id:35744052-6f41-4168-85b9-915b494bb0e3 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: ImageService.__init__() got an unexpected keyword argument 'target_folder_path'
2025-04-09 20:52:57,312 [WARNING] [req_id:3eb8d850-fe15-463d-9595-35ea65687814 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: ImageService.__init__() got an unexpected keyword argument 'target_folder_path'
2025-04-09 20:59:52,103 [WARNING] [req_id:fe978fbb-68fa-404c-8520-5865b0057fef user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: ImageService.__init__() got an unexpected keyword argument 'target_folder_path'
2025-04-09 20:59:52,254 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 20:59:52,256 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 20:59:52,256 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 20:59:52,257 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 20:59:52,257 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 20:59:52,259 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 20:59:54,497 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 20:59:54,515 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 20:59:54,531 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 20:59:54,537 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 20:59:54,539 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 20:59:54,541 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 20:59:54,541 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 20:59:54,542 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 20:59:54,542 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 20:59:54,542 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:29:54.539395+09:00 (in 1799.996988 seconds)
2025-04-09 20:59:56,510 [WARNING] [req_id:2411259b-cce6-4957-942d-69d5e24a46b4 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: FileService.__init__() got an unexpected keyword argument 'target_folder_path'
2025-04-09 20:59:59,341 [WARNING] [req_id:c0f71d98-b6d1-4b56-a9ed-c9100c970b17 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: FileService.__init__() got an unexpected keyword argument 'target_folder_path'
2025-04-09 21:02:04,644 [WARNING] [req_id:9eb2de28-9cf4-4d7c-8ae6-881eb23d93b0 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: FileService.__init__() got an unexpected keyword argument 'target_folder_path'
2025-04-09 21:02:04,854 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:02:04,856 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:02:04,857 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:02:04,857 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:02:04,857 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:02:04,858 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:02:06,702 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:02:06,720 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:02:06,732 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:02:06,738 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:02:06,741 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:02:06,742 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:02:06,743 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:02:06,743 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:02:06,744 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:02:06,744 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:32:06.741273+09:00 (in 1799.996998 seconds)
2025-04-09 21:02:08,271 [INFO] [req_id:6370455a-c852-4aff-8dc4-1ef2ef26b05c user:1] base.py:43 - POST /posts [200] 0.0904s
2025-04-09 21:04:45,868 [INFO] [req_id:d84ae361-a6b2-4fa6-98c5-02fcc53f294d user:1] base.py:43 - GET /posts [200] 0.0345s
2025-04-09 21:04:46,051 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:04:46,053 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:04:46,053 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:04:46,054 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:04:46,054 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:04:46,055 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:04:48,369 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:04:48,388 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:04:48,402 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:04:48,427 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:04:48,428 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:04:48,429 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:04:48,430 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:04:48,430 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:04:48,430 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:04:48,430 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 21:34:48.428988+09:00 (in 1799.998040 seconds)
2025-04-09 21:05:04,024 [INFO] [req_id:cdaa5b69-02bf-478a-9617-ebe7d7a1b5e8 user:1] base.py:43 - GET /posts [200] 0.046s
2025-04-09 21:07:15,087 [WARNING] [req_id:4354f4ea-71de-415b-bc5d-26895ab75d19 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: ÏûÑÏãú ÌååÏùºÏù¥ Ï°¥Ïû¨ÌïòÏßÄ ÏïäÏäµÎãàÎã§.
2025-04-09 21:07:32,864 [WARNING] [req_id:a8ead9b6-24b5-41ab-91c8-c5adabb89baa user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: ÏûÑÏãú ÌååÏùºÏù¥ Ï°¥Ïû¨ÌïòÏßÄ ÏïäÏäµÎãàÎã§.
2025-04-09 21:07:42,436 [INFO] [req_id:bb42126a-cc82-4189-8872-e309ac036965 user:1] base.py:43 - GET /posts [200] 0.0235s
2025-04-09 21:32:02,181 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 21:32:02,183 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 21:32:02,183 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:625 - Calling on_header_value with data[75:151]
2025-04-09 21:32:02,183 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:32:02,184 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:625 - Calling on_header_field with data[153:165]
2025-04-09 21:32:02,184 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:625 - Calling on_header_value with data[167:177]
2025-04-09 21:32:02,184 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:32:02,185 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 21:32:02,185 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:625 - Calling on_part_data with data[181:65717]
2025-04-09 21:32:02,187 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:625 - Calling on_part_data with data[0:262144]
2025-04-09 21:32:02,189 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:625 - Calling on_part_data with data[0:78441]
2025-04-09 21:32:02,189 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 21:32:02,190 [DEBUG] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 21:32:02,196 [INFO] [req_id:d143ae2e-e6ba-4062-a10b-0c4a682120de user:1] base.py:43 - POST /common/image [200] 0.017s
2025-04-09 21:32:02,383 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:32:02,384 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:32:02,384 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:32:02,385 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:32:02,385 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:32:02,386 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:32:04,974 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:32:04,997 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:32:05,016 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:32:05,024 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:32:05,026 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:32:05,028 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:32:05,028 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:32:05,029 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:32:05,029 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:32:05,030 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 22:02:05.026753+09:00 (in 1799.996000 seconds)
2025-04-09 21:32:12,425 [WARNING] [req_id:02212ef8-93dc-405e-979c-049da30c15be user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.uploaded_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 32, 12), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:32:19,132 [WARNING] [req_id:1e7494bb-fa3c-4414-b805-f247afc3db20 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: ÏûÑÏãú ÌååÏùºÏù¥ Ï°¥Ïû¨ÌïòÏßÄ ÏïäÏäµÎãàÎã§.
2025-04-09 21:32:36,599 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 21:32:36,600 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 21:32:36,600 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:625 - Calling on_header_value with data[75:150]
2025-04-09 21:32:36,600 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:32:36,600 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:625 - Calling on_header_field with data[152:164]
2025-04-09 21:32:36,601 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:625 - Calling on_header_value with data[166:176]
2025-04-09 21:32:36,601 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:32:36,601 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 21:32:36,601 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:625 - Calling on_part_data with data[180:65716]
2025-04-09 21:32:36,603 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:625 - Calling on_part_data with data[0:262144]
2025-04-09 21:32:36,604 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:625 - Calling on_part_data with data[0:78441]
2025-04-09 21:32:36,604 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 21:32:36,605 [DEBUG] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 21:32:36,610 [INFO] [req_id:e2ea03b1-36ef-441a-ba49-36c32aa39da6 user:1] base.py:43 - POST /common/files [200] 0.0136s
2025-04-09 21:32:47,514 [WARNING] [req_id:6a9824b5-e735-4264-bb38-6978350860ee user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.uploaded_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 32, 47), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:34:20,356 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 21:34:20,357 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 21:34:20,357 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:625 - Calling on_header_value with data[75:150]
2025-04-09 21:34:20,358 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:34:20,358 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:625 - Calling on_header_field with data[152:164]
2025-04-09 21:34:20,359 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:625 - Calling on_header_value with data[166:176]
2025-04-09 21:34:20,359 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:34:20,359 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 21:34:20,359 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:625 - Calling on_part_data with data[180:261392]
2025-04-09 21:34:20,362 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:625 - Calling on_part_data with data[0:144909]
2025-04-09 21:34:20,362 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 21:34:20,363 [DEBUG] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 21:34:20,367 [INFO] [req_id:c3fd59bf-897f-496a-bf30-32793687556b user:1] base.py:43 - POST /common/files [200] 0.0131s
2025-04-09 21:34:30,080 [WARNING] [req_id:d1e41cb8-ff09-443a-9739-e7e8cd13c8c4 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.uploaded_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 34, 30), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:40:35,589 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:40:35,590 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:40:35,591 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:40:35,591 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:40:35,591 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:40:35,592 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:43:21,631 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:43:21,651 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:43:21,666 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:43:21,672 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:43:21,675 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:43:21,676 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:43:21,676 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:43:21,677 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:43:21,677 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:43:21,677 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 22:13:21.674896+09:00 (in 1799.997000 seconds)
2025-04-09 21:45:01,310 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:628 - Calling on_part_begin with no data
2025-04-09 21:45:01,311 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:625 - Calling on_header_field with data[54:73]
2025-04-09 21:45:01,311 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:625 - Calling on_header_value with data[75:150]
2025-04-09 21:45:01,311 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:45:01,312 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:625 - Calling on_header_field with data[152:164]
2025-04-09 21:45:01,312 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:625 - Calling on_header_value with data[166:176]
2025-04-09 21:45:01,312 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:628 - Calling on_header_end with no data
2025-04-09 21:45:01,312 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:628 - Calling on_headers_finished with no data
2025-04-09 21:45:01,312 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:625 - Calling on_part_data with data[180:65716]
2025-04-09 21:45:01,314 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:625 - Calling on_part_data with data[0:262144]
2025-04-09 21:45:01,315 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:625 - Calling on_part_data with data[0:78441]
2025-04-09 21:45:01,316 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:628 - Calling on_part_end with no data
2025-04-09 21:45:01,316 [DEBUG] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] multipart.py:628 - Calling on_end with no data
2025-04-09 21:45:01,321 [INFO] [req_id:159626e7-b347-4f1c-90c9-cf55f7812809 user:1] base.py:43 - POST /common/files [200] 0.0129s
2025-04-09 21:45:11,716 [INFO] [req_id:a9c7fb6d-b34e-4cec-a553-bee66129ce5f user:1] base.py:43 - POST /posts [200] 0.0927s
2025-04-09 21:46:55,470 [INFO] [req_id:0b1efed7-f2f4-48b2-a730-660abf9162fe user:1] base.py:43 - GET /posts [200] 0.0256s
2025-04-09 21:46:55,621 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:46:55,622 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:46:55,623 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:46:55,623 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:46:55,624 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:46:55,625 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:46:57,598 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:46:57,619 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:46:57,635 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:46:57,644 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:46:57,646 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:46:57,648 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:46:57,648 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:46:57,648 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:46:57,649 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:46:57,649 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 22:16:57.646578+09:00 (in 1799.996786 seconds)
2025-04-09 21:47:02,613 [WARNING] [req_id:d3151282-eb20-4dab-867c-bda98ab623db user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.created_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 45, 11), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:47:04,069 [WARNING] [req_id:fed29436-237b-4657-9203-be9e24d9b661 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.created_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 45, 11), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:47:05,475 [WARNING] [req_id:d87c1130-f7c6-46be-8855-66b4eb9ceaef user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.created_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 45, 11), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:47:10,500 [WARNING] [req_id:9ecd63d6-f232-475b-8f7f-35aa145da7f2 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.created_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 45, 11), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:47:10,715 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:47:10,715 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:47:10,716 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:47:10,716 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:47:10,716 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:47:10,718 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:47:12,768 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:47:12,792 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:47:12,813 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:47:12,840 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:47:12,842 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:47:12,844 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:47:12,845 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:47:12,845 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:47:12,847 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:47:12,848 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 22:17:12.842202+09:00 (in 1799.994943 seconds)
2025-04-09 21:47:12,898 [INFO] [req_id:beeda528-8756-4f9f-8c94-836c75751047 user:1] base.py:43 - GET /posts [200] 0.0372s
2025-04-09 21:47:42,941 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:47:42,942 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:47:42,943 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:47:42,943 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:47:42,943 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:47:42,944 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:47:44,886 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:47:44,905 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:47:44,927 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:47:44,933 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:47:44,936 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:47:44,937 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:47:44,938 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:47:44,938 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:47:44,938 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:47:44,938 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 22:17:44.935612+09:00 (in 1799.996929 seconds)
2025-04-09 21:47:47,798 [WARNING] [req_id:fe7d52ad-7453-4289-8435-086f345cebcb user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.created_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 45, 11), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:51:09,710 [WARNING] [req_id:bd13126d-1276-49a2-bb7e-6915b45fd3c4 user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: 1 validation error for PostSchema
files.0.created_at
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 4, 9, 12, 45, 11), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
2025-04-09 21:51:09,831 [INFO] [req_id:None user:None] lifespan.py:29 - üì¥ Shutting down...
2025-04-09 21:51:09,832 [INFO] [req_id:None user:None] graceful_shutdown.py:7 - üßπ Performing graceful shutdown tasks
2025-04-09 21:51:09,832 [INFO] [req_id:None user:None] graceful_shutdown.py:11 - üõë APScheduler stopped
2025-04-09 21:51:09,833 [INFO] [req_id:None user:None] graceful_shutdown.py:33 - üßº Graceful shutdown completed
2025-04-09 21:51:09,834 [INFO] [req_id:None user:None] lifespan.py:33 - ‚úÖ Cleanup done. Bye üëã
2025-04-09 21:51:09,835 [INFO] [req_id:None user:None] base.py:245 - Scheduler has been shut down
2025-04-09 21:51:12,274 [INFO] [req_id:None user:None] lifespan.py:15 - üöÄ Starting up...
2025-04-09 21:51:12,296 [DEBUG] [req_id:None user:None] connection.py:951 - caching sha2: succeeded by fast path.
2025-04-09 21:51:12,316 [INFO] [req_id:None user:None] startup_check.py:16 - ‚úÖ Database connected successfully
2025-04-09 21:51:12,323 [INFO] [req_id:None user:None] startup_check.py:27 - ‚úÖ Redis connected successfully
2025-04-09 21:51:12,325 [INFO] [req_id:None user:None] base.py:507 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-04-09 21:51:12,328 [INFO] [req_id:None user:None] base.py:1090 - Added job "cleanup_temp_images" to job store "default"
2025-04-09 21:51:12,328 [INFO] [req_id:None user:None] base.py:214 - Scheduler started
2025-04-09 21:51:12,328 [INFO] [req_id:None user:None] lifespan.py:22 - üîó All services connected.
2025-04-09 21:51:12,329 [DEBUG] [req_id:None user:None] base.py:1151 - Looking for jobs to run
2025-04-09 21:51:12,329 [DEBUG] [req_id:None user:None] base.py:1258 - Next wakeup is due at 2025-04-09 22:21:12.325603+09:00 (in 1799.996428 seconds)
2025-04-09 21:51:12,380 [INFO] [req_id:02449f82-f317-484f-b56b-15cfc835bb00 user:1] base.py:43 - GET /posts [200] 0.0371s
2025-04-09 22:07:33,507 [WARNING] [req_id:83261e70-a0e0-47e3-a479-a48219a860dd user:1] base.py:46 - [REQUEST_LOGGER] Ï≤òÎ¶¨ Ïã§Ìå®: A transaction is already begun on this Session.
2025-04-09 22:07:38,201 [INFO] [req_id:07a1084a-dd17-425b-832b-8dad8fe0e663 user:1] base.py:43 - GET /posts [200] 0.0214s
2025-04-09 22:07:52,371 [INFO] [req_id:cb18012b-393b-4cba-b29b-db67dca3bb10 user:1] base.py:43 - DELETE /posts/113 [200] 0.0474s
